src/web/Controllers/CalendarController.cs
using AAE.RESS.Application;
using AAE.RESS.Interfaces;
using AAE.RESS.Web.ViewModels;
using Ical.Net.CalendarComponents;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AAE.RESS.Web.Controllers
{
    public class CalendarController : Controller
    {
        private readonly IResourceService _resourceService;
        private readonly ICalendarRepository _calendarRepository;
        public CalendarController(IResourceService resourceService, ICalendarRepository calendarRepository)
        {
            _resourceService = resourceService ?? throw new ArgumentNullException(nameof(resourceService));
            _calendarRepository = calendarRepository ?? throw new ArgumentNullException(nameof(calendarRepository));
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}/calendar")]
        public async Task<IActionResult> Index(string type, string url)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));


            var resource = await _resourceService.GetAsync(url, rType);

            var vm = new CalendarViewModel(resource);

            return View(vm);
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}/calendar/ics")]
        public async Task<IActionResult> Ics(string type, string url, [FromQuery] DateTimeOffset start, [FromQuery] DateTimeOffset end)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));

            var vevents = await _calendarRepository.GetEventsAsync(rType, url);

            var non_recurring_vevents = vevents.Where(ev => ev.DtStart.AsDateTimeOffset <= end
                                        && ev.DtEnd.AsDateTimeOffset >= start
                                        && ev.RecurrenceRules.Count == 0
                                        ).ToList();

            // this will be used to search for "exceptions" to recurring events
            var recurring_exceptions = non_recurring_vevents.Where(ev => ev.RecurrenceId != null)
                                            .ToList();

            var occurrences = vevents
                        .Where(ev => ev.RecurrenceRules.Count > 0)
                        .AsParallel()
                        .SelectMany(e => e.GetOccurrences(start.DateTime, end.DateTime))
                        .Distinct()
                        .ToList();

            IList<FullCalendarEvent> out_events = new List<FullCalendarEvent>();
            FullCalendarEvent out_event;

            // loop through non-recurring events
            foreach (var vevent in non_recurring_vevents)
            {
                out_event = new FullCalendarEvent()
                {
                    id = vevent.Uid,
                    allDay = vevent.IsAllDay,
                    start = vevent.DtStart.AsDateTimeOffset,
                    end = vevent.DtEnd.AsDateTimeOffset,
                    // title = vevent.Properties.Get<string>("X-MICROSOFT-CDO-BUSYSTATUS")
                    title = vevent.Summary

                };

                out_events.Add(out_event);
            }

            // loop through recurring event occurences
            foreach (var occurrence in occurrences)
            {
                var vevent = (CalendarEvent)occurrence.Source;

                // are there any exceptions for this particular occurrence?
                // criteria is UID match and DtStart is the same day (not necessarily the time)
                // https://www.kanzaki.com/docs/ical/recurrenceId.html

                var vevent_occurence_exception = recurring_exceptions.Where(ev => ev.Uid == vevent.Uid &&
                                                                             ev.DtStart.Date == occurrence.Period.StartTime.Date)
                                                                             .FirstOrDefault();

                if (vevent_occurence_exception == null)
                {
                    out_event = new FullCalendarEvent()
                    {
                        id = vevent.Uid,
                        allDay = vevent.IsAllDay,
                        start = occurrence.Period.StartTime.AsDateTimeOffset,
                        end = occurrence.Period.EndTime.AsDateTimeOffset,
                        title = vevent.Summary
                    };

                    out_events.Add(out_event);
                }

            }

            return Json(out_events);
        }

    }
}

src/web/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.RESS.Application;
using AAE.RESS.Interfaces;
using AAE.RESS.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class InfoController : Controller
    {
        private readonly IRoomQueries _roomQueries;
        private readonly IEquipmentQueries _equipmentQueries;

        public InfoController(IRoomQueries roomQueries, IEquipmentQueries equipmentQueries)
        {
            _roomQueries = roomQueries ?? throw new ArgumentNullException(nameof(roomQueries));
            _equipmentQueries = equipmentQueries ?? throw new ArgumentNullException(nameof(equipmentQueries));
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}")]
        public async Task<IActionResult> Index(string type, string url)
        {
            if (type == "rooms")
            {
                var room = await _roomQueries.GetAsync(url);
                if (room == null)
                    return NotFound();
                var vm = new InfoRoomViewModel() { Room = room };
                return View("Room", vm);
            }
            else if (type == "equipment")
            {
                var equipment = await _equipmentQueries.GetAsync(url);
                if (equipment == null)
                    return NotFound();
                var vm = new InfoEquipmentViewModel() { Equipment = equipment };
                return View("Equipment", vm);
            }
            else
                return NotFound();

        }
    }
}

src/web/Controllers/ReserveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.Identity;
using AAE.RESS.Application;
using AAE.RESS.Application.Reserve;
using AAE.RESS.Interfaces;
using AAE.RESS.Security.Identity;
using AAE.RESS.Web.ViewModels;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class ReserveController : Controller
    {
        private readonly IResourceService _resourceService;
        private readonly IReservationProcessor _reservationProcessor;
        private readonly IAuthorizationService _authorizationService;

        public ReserveController(IResourceService resourceService, IAuthorizationService authorizationService, IReservationProcessor reservationProcessor)
        {
            _resourceService = resourceService ?? throw new ArgumentNullException(nameof(resourceService));
            _reservationProcessor = reservationProcessor ?? throw new ArgumentNullException(nameof(reservationProcessor));
            _authorizationService = authorizationService ?? throw new ArgumentNullException(nameof(authorizationService));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="type"></param>
        /// <param name="url"></param>
        /// <remarks>requireSession must be enabled in shibboleth2.xml on webserver.  Path is hardcoded, so it must be changed if route attributes are changed</remarks>
        [Authorize]
        [HttpGet("{type:regex(rooms|equipment)}/{url}/reserve")]
        public async Task<IActionResult> Index(string type, string url)
        {
            // does the user have an email?  It is required.
            // FERPA students will not
            var currentUser = new RESSUser(HttpContext.User);
            if (currentUser.Email == null)
                return RedirectToAction("NoEmail", "Error");


            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));


            var resource = await _resourceService.GetAsync(url, rType);

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, resource, "ResourceReserve");
            if (authorizationResult.Succeeded)
            {
                var vm = new ReserveViewModel(resource);

                return View(vm);
            }
            else
            {
                return new ForbidResult();
            }
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}/success")]
        public async Task<IActionResult> Success(string type, string url)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));


            var resource = await _resourceService.GetAsync(url, rType);

            var vm = new ReserveViewModel(resource);

            return View(vm);
        }

        [Authorize]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [HttpPost("{type:regex(rooms|equipment)}/{url}/reserve")]
        public async Task<IActionResult> Reserve(string type, string url, [FromBody] ReserveInput input)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));

            var loginUser = new ClaimsApplicationUser(User);
            var resource = await _resourceService.GetAsync(url, rType);

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, resource, "ResourceReserve");
            if (authorizationResult.Succeeded)
            {
                var inputStartDate = Convert.ToDateTime(input.startDate + ' ' + input.startTime);
                var inputEndDate = Convert.ToDateTime(input.endDate + ' ' + input.endTime);

                var vEvent = new CalendarEvent()
                {
                    // include the time no matter what - it will be ignore if isAllDay=true
                    Start = new CalDateTime(inputStartDate, "America/Chicago"),
                    End = new CalDateTime(inputEndDate, "America/Chicago"),
                    IsAllDay = input.isAllDay,
                    Summary = input.title,
                    Description = input.descr
                };

                // check for recurrence
                var frequency = input.frequency.ToLower();
                if (frequency != "never")
                {
                    RecurrencePattern rrule;

                    switch (frequency)
                    {
                        case "weekly":
                            rrule = new RecurrencePattern(FrequencyType.Weekly, input.recurInterval)
                            {
                                ByDay = DaysToICalDays(input.byDay)
                            };

                            break;
                        case "monthly":
                            rrule = new RecurrencePattern(FrequencyType.Monthly, input.recurInterval);

                            if (input.monthlyRepeatOn == "day")
                            {
                                rrule.ByMonthDay = new List<int>() { input.recurMonthDay };
                            }
                            else if (input.monthlyRepeatOn == "weekday")
                            {
                                rrule.BySetPosition = new List<int>() { input.recurWeekDayOffset };
                                rrule.ByDay = new List<WeekDay>() { new WeekDay(input.recurWeekDay) };
                            }
                            else
                                throw new ArgumentException("monthlyRepeatOn must specify day or weekday");
                            break;
                        default:
                            throw new ArgumentOutOfRangeException($"Recurrence frequency {frequency} not supported.");
                    }

                    //End
                    if (input.repeatEnd == "after")
                    {
                        rrule.Count = input.endAfter;
                    }
                    else if (input.repeatEnd == "on")
                    {
                        if (DateTime.TryParse(input.repeatUntil, out DateTime until))
                            rrule.Until = until;
                        else
                            throw new ArgumentException("repeatUntil is not a vaild date");
                    }

                    // if "never ends", then just don't set anything

                    vEvent.RecurrenceRules = new List<RecurrencePattern>() { rrule };
                }


                var request = new ReservationRequest(vEvent, resource, loginUser);
                await _reservationProcessor.Process(request);

                return NoContent();
            }
            else
            {
                return new ForbidResult();
            }

        }

        /// <summary>
        /// Converts a string of UW day(s) to a list of ICal DayOfWeek
        /// </summary>
        /// <param name="days"></param>
        /// <returns></returns>
        private List<WeekDay> UWDaysToICalDays(string days)
        {
            var arDays = days.Split();
            var lstDays = new List<WeekDay>();
            foreach (var day in arDays)
            {
                lstDays.Add(new WeekDay(UWDayToICalDay(day)));
            }

            return lstDays;
        }

        /// <summary>
        /// Converts an array of day(s) to a list of ICal DayOfWeek
        /// </summary>
        /// <param name="days">in the format MO, TU, WE, etc</param>
        private List<WeekDay> DaysToICalDays(string[] days)
        {
            var lstDays = new List<WeekDay>();
            foreach (var day in days)
            {
                lstDays.Add(new WeekDay(day));
            }

            return lstDays;
        }

        /// <summary>
        /// Converts a UW day into a <see cref="DayOfWeek"/>
        /// </summary>
        private DayOfWeek UWDayToICalDay(string day)
        {
            switch (day.ToUpper())
            {
                case "M":
                    return DayOfWeek.Monday;
                case "T":
                    return DayOfWeek.Tuesday;
                case "W":
                    return DayOfWeek.Wednesday;
                case "R":
                    return DayOfWeek.Thursday;
                case "F":
                    return DayOfWeek.Friday;
                case "S":
                    return DayOfWeek.Saturday;
                case "N":
                    return DayOfWeek.Sunday;
                default:
                    throw new ArgumentOutOfRangeException(nameof(day));
            }
        }
    }
}

src/web/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.RESS.Application;
using AAE.RESS.Interfaces;
using AAE.RESS.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class TypeController : Controller
    {
        IResourceService _resourceService;

        public TypeController(IResourceService resourceService)
        {
            _resourceService = resourceService ?? throw new ArgumentNullException(nameof(resourceService));
        }

        [HttpGet("{type:regex(rooms|equipment)}")]
        public async Task<IActionResult> Index(string type)
        {
            ResourceType rType;
            string rTypeText = string.Empty;
            if (type == "rooms")
            {
                rType = ResourceType.Room;
                rTypeText = "Rooms";
            }
            else if (type == "equipment")
            {
                rType = ResourceType.Equipment;
                rTypeText = "Equipment";
            }
            else
                throw new ArgumentOutOfRangeException(nameof(type));

            var resources = await _resourceService.GetAsync(rType);

            var vm = new TypeViewModel() 
            { 
                ResourceType = rType,
                ResourceTypeText = rTypeText,
                Resources = resources
            };

            return View(vm);
        }
    }
}

src/web/Views/Info/Equipment.cshtml
@model AAE.RESS.Web.ViewModels.InfoEquipmentViewModel
@{
    ViewData["Title"] = @Model.Equipment.FullName;
}

@section breadcrumbs {

    <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Rooms</a></li>
    <li>@Model.Equipment.FullName</li>
}
<div class="uw-full-row container" id="js-vue-app">
    <div class="uw-row">
        <h1 class="page-title uw-mini-bar" id="hdr">@Model.Equipment.FullName</h1>
    </div>
    <div class="uw-row">
        <div class="col-xl-4">
            <div class="equipment-location">Location: @Model.Equipment.Location</div>
            <div class="equipment-description">@Html.Raw(Model.Equipment.Description.Replace("\r\n", "<br />"))</div>

        </div>
        <div class="col-md-2 text-center">
            <a asp-action="Index" asp-controller="Calendar" asp-route-url="@Model.Equipment.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">
                <img src="~/img/calendar-icon.png" class="listing-action-icon" alt="Calendar for @Model.Equipment.FullName" /><br />
                Calendar
            </a>
        </div>
        <div class="col-md-2 text-center">
            @if (Model.Equipment.CanReserve)
            {
            <a asp-action="Index" asp-controller="Reserve" asp-route-url="@Model.Equipment.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">
                <img src="~/img/reserve-icon.svg" class="listing-action-icon" alt="Reserve @Model.Equipment.FullName" /><br />
                Reserve<br /><span class="netid-required">(NetID required)</span>
            </a>
            }
        </div>
    </div>
    <div class="uw-row mt-5">
        @foreach (var img in Model.Equipment.Images)
        {
            <div class="col-lg-3 col-md-4 col-sm-6">
                <img url="@img.Uri.Thumbnail" hi-res-url="@img.Uri.FullHd" link-to="true" class="gallery-image" click-handler="linkClickHandler" />
            </div>
        }
    </div>

    <modal-picture-viewer ref="pictureViewer" 
                          :pictureurl="modalPictureUrl" 
                          v-show="pictureViewerShow"
                          v-on:close="onModalClose"></modal-picture-viewer>
</div>


@section mastercss {

    <environment excludes="Development">
        <link asp-href-include="~/assets/index-*.css" rel="stylesheet" media="all" />
    </environment>
}

@section masterjs{


    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/pages.info.index-*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/pages/info/index/index.js"></script>
    </environment>
}

src/web/Views/Info/Room.cshtml
@model AAE.RESS.Web.ViewModels.InfoRoomViewModel
@{
    ViewData["Title"] = @Model.Room.DisplayName;
}



@section breadcrumbs {

    <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Rooms</a></li>
    <li>@Model.Room.DisplayName</li>
}
<div class="uw-full-row container" id="js-vue-app">
    <div class="uw-row">
        <h1 class="page-title uw-mini-bar" id="hdr">@Model.Room.DisplayName</h1>
    </div>
    <div class="uw-row">
        <div class="col-xl-4">
            <div class="row">
                <div class="col-12">
                    <div class="room-building-number">@Model.Room.RoomNumber @Model.Room.BuildingName (@Model.Room.BuildingNumber)</div>
                    <div class="room-type">@Model.Room.RoomType</div>
                    <div class="capacity">Capacity: @Model.Room.Capacity</div>
                    <div class="room-description">@Html.Raw(Model.Room.Description.Replace("\r\n", "<br />"))</div>
                </div>

            </div>
            <div class="row mt-3">
                <div class="col-4 text-center">
                    <a asp-action="Index" asp-controller="Calendar" asp-route-url="@Model.Room.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">
                        <img src="~/img/calendar-icon.png" class="listing-action-icon" alt="Calendar for @Model.Room.DisplayName" /><br />
                        Calendar
                    </a>
                </div>
                <div class="col-4 text-center">
                    @if (Model.Room.CanReserve)
                    {
                        <a asp-action="Index" asp-controller="Reserve" asp-route-url="@Model.Room.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">
                            <img src="~/img/reserve-icon.svg" class="listing-action-icon" alt="Reserve @Model.Room.DisplayName" /><br />
                            Reserve<br /><span class="netid-required">(NetID required)</span>
                        </a>
                    }
                </div>
                <div class="col-4 text-center">
                    @if (Model.Room.CanReserve)
                    {
                        <a href="https://kb.wisc.edu/aae/101619">
                            <img src="~/img/office.png" class="listing-action-icon" alt="Reserve @Model.Room.DisplayName with Office 365" /><br />
                            Reserve with<br />Office 365
                        </a>
                    }
                </div>
            </div>

        </div>
        <div class="col-xl-8">
            @if (Model.Room.MapImage != null)
            {
                <img url="@Model.Room.MapImage.Uri.Desktop" hi-res-url="@Model.Room.MapImage.Uri.FullHd" link-to="true" click-handler="linkClickHandler" />
            }
        </div>
    </div>
    <div class="uw-row mt-5">
        @foreach (var img in Model.Room.Images)
        {
            <div class="col-lg-3 col-md-4 col-sm-6">
                <img url="@img.Uri.Thumbnail" hi-res-url="@img.Uri.FullHd" link-to="true" class="gallery-image" click-handler="linkClickHandler" />
            </div>
        }
    </div>

    <modal-picture-viewer ref="pictureViewer" 
                          :pictureurl="modalPictureUrl" 
                          v-show="pictureViewerShow"
                          v-on:close="onModalClose"></modal-picture-viewer>
</div>

@section mastercss {

    <environment excludes="Development">
        <link asp-href-include="~/assets/index-*.css" rel="stylesheet" media="all" />
    </environment>
}

@section masterjs{


    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/pages.info.index-*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/pages/info/index/index.js"></script>
    </environment>
}