src/web/ViewModels/ReserveViewModel.cs
using AAE.RESS.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AAE.RESS.Web.ViewModels
{
    public class ReserveViewModel
    {
        public ReserveViewModel(IResource resource)
        {
            Resource = resource;
        }
        public IResource Resource { get; set; }
    }
}

src/web/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.RESS.Application;
using AAE.RESS.Interfaces;
using AAE.RESS.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class InfoController : Controller
    {
        private readonly IRoomQueries _roomQueries;
        private readonly IEquipmentQueries _equipmentQueries;

        public InfoController(IRoomQueries roomQueries, IEquipmentQueries equipmentQueries)
        {
            _roomQueries = roomQueries ?? throw new ArgumentNullException(nameof(roomQueries));
            _equipmentQueries = equipmentQueries ?? throw new ArgumentNullException(nameof(equipmentQueries));
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}")]
        public async Task<IActionResult> Index(string type, string url)
        {
            if (type == "rooms")
            {
                var room = await _roomQueries.GetAsync(url);
                if (room == null)
                    return NotFound();
                var vm = new InfoRoomViewModel() { Room = room };
                return View("Room", vm);
            }
            else if (type == "equipment")
            {
                var equipment = await _equipmentQueries.GetAsync(url);
                if (equipment == null)
                    return NotFound();
                var vm = new InfoEquipmentViewModel() { Equipment = equipment };
                return View("Equipment", vm);
            }
            else
                return NotFound();

        }
    }
}

src/web/Controllers/ReserveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.Identity;
using AAE.RESS.Application;
using AAE.RESS.Application.Reserve;
using AAE.RESS.Interfaces;
using AAE.RESS.Security.Identity;
using AAE.RESS.Web.ViewModels;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class ReserveController : Controller
    {
        private readonly IResourceService _resourceService;
        private readonly IReservationProcessor _reservationProcessor;
        private readonly IAuthorizationService _authorizationService;

        public ReserveController(IResourceService resourceService, IAuthorizationService authorizationService, IReservationProcessor reservationProcessor)
        {
            _resourceService = resourceService ?? throw new ArgumentNullException(nameof(resourceService));
            _reservationProcessor = reservationProcessor ?? throw new ArgumentNullException(nameof(reservationProcessor));
            _authorizationService = authorizationService ?? throw new ArgumentNullException(nameof(authorizationService));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="type"></param>
        /// <param name="url"></param>
        /// <remarks>requireSession must be enabled in shibboleth2.xml on webserver.  Path is hardcoded, so it must be changed if route attributes are changed</remarks>
        [Authorize]
        [HttpGet("{type:regex(rooms|equipment)}/{url}/reserve")]
        public async Task<IActionResult> Index(string type, string url)
        {
            // does the user have an email?  It is required.
            // FERPA students will not
            var currentUser = new RESSUser(HttpContext.User);
            if (currentUser.Email == null)
                return RedirectToAction("NoEmail", "Error");


            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));


            var resource = await _resourceService.GetAsync(url, rType);

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, resource, "ResourceReserve");
            if (authorizationResult.Succeeded)
            {
                var vm = new ReserveViewModel(resource);

                return View(vm);
            }
            else
            {
                return new ForbidResult();
            }
        }

        [HttpGet("{type:regex(rooms|equipment)}/{url}/success")]
        public async Task<IActionResult> Success(string type, string url)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));


            var resource = await _resourceService.GetAsync(url, rType);

            var vm = new ReserveViewModel(resource);

            return View(vm);
        }

        [Authorize]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [HttpPost("{type:regex(rooms|equipment)}/{url}/reserve")]
        public async Task<IActionResult> Reserve(string type, string url, [FromBody] ReserveInput input)
        {
            ResourceType rType;
            if (type == "rooms")
                rType = ResourceType.Room;
            else if (type == "equipment")
                rType = ResourceType.Equipment;
            else
                throw new ArgumentOutOfRangeException(nameof(type));

            var loginUser = new ClaimsApplicationUser(User);
            var resource = await _resourceService.GetAsync(url, rType);

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, resource, "ResourceReserve");
            if (authorizationResult.Succeeded)
            {
                var inputStartDate = Convert.ToDateTime(input.startDate + ' ' + input.startTime);
                var inputEndDate = Convert.ToDateTime(input.endDate + ' ' + input.endTime);

                var vEvent = new CalendarEvent()
                {
                    // include the time no matter what - it will be ignore if isAllDay=true
                    Start = new CalDateTime(inputStartDate, "America/Chicago"),
                    End = new CalDateTime(inputEndDate, "America/Chicago"),
                    IsAllDay = input.isAllDay,
                    Summary = input.title,
                    Description = input.descr
                };

                // check for recurrence
                var frequency = input.frequency.ToLower();
                if (frequency != "never")
                {
                    RecurrencePattern rrule;

                    switch (frequency)
                    {
                        case "weekly":
                            rrule = new RecurrencePattern(FrequencyType.Weekly, input.recurInterval)
                            {
                                ByDay = DaysToICalDays(input.byDay)
                            };

                            break;
                        case "monthly":
                            rrule = new RecurrencePattern(FrequencyType.Monthly, input.recurInterval);

                            if (input.monthlyRepeatOn == "day")
                            {
                                rrule.ByMonthDay = new List<int>() { input.recurMonthDay };
                            }
                            else if (input.monthlyRepeatOn == "weekday")
                            {
                                rrule.BySetPosition = new List<int>() { input.recurWeekDayOffset };
                                rrule.ByDay = new List<WeekDay>() { new WeekDay(input.recurWeekDay) };
                            }
                            else
                                throw new ArgumentException("monthlyRepeatOn must specify day or weekday");
                            break;
                        default:
                            throw new ArgumentOutOfRangeException($"Recurrence frequency {frequency} not supported.");
                    }

                    //End
                    if (input.repeatEnd == "after")
                    {
                        rrule.Count = input.endAfter;
                    }
                    else if (input.repeatEnd == "on")
                    {
                        if (DateTime.TryParse(input.repeatUntil, out DateTime until))
                            rrule.Until = until;
                        else
                            throw new ArgumentException("repeatUntil is not a vaild date");
                    }

                    // if "never ends", then just don't set anything

                    vEvent.RecurrenceRules = new List<RecurrencePattern>() { rrule };
                }


                var request = new ReservationRequest(vEvent, resource, loginUser);
                await _reservationProcessor.Process(request);

                return NoContent();
            }
            else
            {
                return new ForbidResult();
            }

        }

        /// <summary>
        /// Converts a string of UW day(s) to a list of ICal DayOfWeek
        /// </summary>
        /// <param name="days"></param>
        /// <returns></returns>
        private List<WeekDay> UWDaysToICalDays(string days)
        {
            var arDays = days.Split();
            var lstDays = new List<WeekDay>();
            foreach (var day in arDays)
            {
                lstDays.Add(new WeekDay(UWDayToICalDay(day)));
            }

            return lstDays;
        }

        /// <summary>
        /// Converts an array of day(s) to a list of ICal DayOfWeek
        /// </summary>
        /// <param name="days">in the format MO, TU, WE, etc</param>
        private List<WeekDay> DaysToICalDays(string[] days)
        {
            var lstDays = new List<WeekDay>();
            foreach (var day in days)
            {
                lstDays.Add(new WeekDay(day));
            }

            return lstDays;
        }

        /// <summary>
        /// Converts a UW day into a <see cref="DayOfWeek"/>
        /// </summary>
        private DayOfWeek UWDayToICalDay(string day)
        {
            switch (day.ToUpper())
            {
                case "M":
                    return DayOfWeek.Monday;
                case "T":
                    return DayOfWeek.Tuesday;
                case "W":
                    return DayOfWeek.Wednesday;
                case "R":
                    return DayOfWeek.Thursday;
                case "F":
                    return DayOfWeek.Friday;
                case "S":
                    return DayOfWeek.Saturday;
                case "N":
                    return DayOfWeek.Sunday;
                default:
                    throw new ArgumentOutOfRangeException(nameof(day));
            }
        }
    }
}

src/web/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AAE.RESS.Application;
using AAE.RESS.Interfaces;
using AAE.RESS.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AAE.RESS.Web.Controllers
{
    public class TypeController : Controller
    {
        IResourceService _resourceService;

        public TypeController(IResourceService resourceService)
        {
            _resourceService = resourceService ?? throw new ArgumentNullException(nameof(resourceService));
        }

        [HttpGet("{type:regex(rooms|equipment)}")]
        public async Task<IActionResult> Index(string type)
        {
            ResourceType rType;
            string rTypeText = string.Empty;
            if (type == "rooms")
            {
                rType = ResourceType.Room;
                rTypeText = "Rooms";
            }
            else if (type == "equipment")
            {
                rType = ResourceType.Equipment;
                rTypeText = "Equipment";
            }
            else
                throw new ArgumentOutOfRangeException(nameof(type));

            var resources = await _resourceService.GetAsync(rType);

            var vm = new TypeViewModel() 
            { 
                ResourceType = rType,
                ResourceTypeText = rTypeText,
                Resources = resources
            };

            return View(vm);
        }
    }
}

src/web/Views/Reserve/Index.cshtml
@model AAE.RESS.Web.ViewModels.ReserveViewModel
@{
    ViewData["Title"] = "Reserve - " + @Model.Resource.DisplayName;
}

@section breadcrumbs {

    @if (Model.Resource.ResourceType == ResourceType.Room)
    {
        <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Rooms</a></li>
    }
    @if (Model.Resource.ResourceType == ResourceType.Equipment)
    {
        <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Equipment</a></li>
    }
    <li><a asp-controller="Info" asp-action="Index" asp-route-url="@Model.Resource.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">@Model.Resource.DisplayName</a></li>
    <li>Reserve</li>
}
<div id="js-vue-app" data-endpoint="@Url.Action("Reserve", "Reserve", new { type = ViewContext.RouteData.Values["type"].ToString(), url = Model.Resource.Url })" 
                    data-uniqueid="@ViewBag.User.UniqueID"
                    data-successurl="@Url.Action("Success", "Reserve", new { type = ViewContext.RouteData.Values["type"].ToString(), url = Model.Resource.Url })">
    <div class="uw-full-row">
        <div class="uw-row">
            <h1 class="page-title uw-mini-bar" id="hdr">Reserve @Model.Resource.DisplayName</h1>
        </div>
        <div class="uw-row">
            <div class="alert alert-info" role="alert">
                If you use Outlook (either the Desktop App or Web App), it is recommended you use that to reserve rooms or equipment.   More information available at <a href="https://kb.wisc.edu/aae/101619" target="_blank" class="alert-link">https://kb.wisc.edu/aae/101619</a>
            </div>
        </div>
        <div class="uw-row">
            <form class="col-sm-12">
                <div class="form-group row" :class="{ 'form-group--error': !datesValid }">
                    <label for="txtStartDate" class="col-xl-1 col-form-label">Start time</label>
                    <div class="col-xl-2">
                        <form-date-picker datepickerid="txtStartDate" 
                                          v-model="reserveRequest.startDate" 
                                          :notyping="true"></form-date-picker>
                    </div>
                    <div class="col-xl-5">
                        <time-picker idprefix="ddStart"
                                     v-model="reserveRequest.startTime"
                                     :inputdisabled="reserveRequest.isAllDay" />

                    </div>
                </div>
                
                <div class="form-group row" :class="{ 'form-group--error': !datesValid }">
                    <label for="txtEndDate" class="col-xl-1 col-form-label">End time</label>
                    <div class="col-xl-2">
                        <form-date-picker datepickerid="txtEndDate"
                                          v-model="reserveRequest.endDate"
                                           :notyping="true"></form-date-picker>

                    </div>
                    <div class="col-xl-5">
                        <time-picker idprefix="ddEnd"
                                     v-model="reserveRequest.endTime"
                                     :inputdisabled="reserveRequest.isAllDay" />

                    </div>
                    <div class="col-xl-4"></div>
                    <div class="col-xl-11 offset-xl-1">
                        <div class="validation-error" v-show="!startDateNotBeforeEndDate">The start date/time must be BEFORE the end date/time.</div>
                    </div>
                    

                </div>
                <div class="form-group row" :class="{ 'form-group--error': !validations.title.required }">
                    <label for="txtTitle" class="col-xl-1 col-form-label">Title</label>
                    <div class="col-sm-11">
                        <input type="text" class="form-control" id="txtTitle" placeholder="Title of event/meeting" v-model="reserveRequest.title" />
                        <div class="validation-error offset-xl-1" v-show="!validations.title.required">This field is required.</div>
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-xl-1">All day</div>
                    <div class="col-xl-11">
                        <toggle-button :value="false"
                                       :sync="true"
                                       v-model="reserveRequest.isAllDay" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="ddRepeat" class="col-xl-1 col-form-label">Repeat</label>
                    <div class="col-xl-2">
                        <select id="ddRepeat" class="custom-select" v-model="reserveRequest.frequency">
                            <option value="never" selected="selected">Never</option>
                            <option value="weekly">Weekly</option>
                            <option value="monthly">Monthly</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row" v-show="frequencyNever == false">
                    <label for="txtRepeatEvery" class="col-xl-1 col-form-label">Repeat every</label>
                    <div class="col-xl-6">
                        <vue-number-input v-model="reserveRequest.recurInterval"
                                          inline
                                          controls
                                          size="small"
                                          :center="true"></vue-number-input>
                        <template v-if="frequencyWeekly == true">
                            week(s)
                        </template>
                        <template v-if="frequencyMonthly == true">
                            month(s)
                        </template>
                    </div>
                </div>

                <div class="form-group row" v-show="frequencyWeekly == true">
                    <label for="" class="col-xl-1 col-form-label">Repeat on</label>
                    <div class="col-xl-8">
                        <day-picker v-model="reserveRequest.byDay"/>
                    </div>
                </div>
                <div class="form-group row" v-show="frequencyMonthly == true">
                    <label for="" class="col-xl-1 col-form-label">Repeat on</label>
                    <div class="col-xl-8">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="repeatOn" id="rbMontlyRepeatOnDay" value="day" v-model="reserveRequest.monthlyRepeatOn">
                            <label class="form-check-label" for="rbMontlyRepeatOnDay">
                                Day
                            </label>
                            <vue-number-input v-model="reserveRequest.recurMonthDay"
                                              inline
                                              controls
                                              size="small"
                                              :min="1" 
                                              :max="31"
                                              :disabled="!repeatOnDay"
                                              :center="true"></vue-number-input>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="repeatOn" id="rbMontlyRepeatOnWeekday" value="weekday" v-model="reserveRequest.monthlyRepeatOn">
                            <week-day-picker :offsetvalue="reserveRequest.recurWeekDayOffset"
                                             :dayvalue="reserveRequest.recurWeekDay"
                                             idprefix="ddMonthlyRecur"
                                             :inputdisabled="!repeatOnWeekday"
                                             v-on:update:values="recurWeekdayInput" />
                        </div>

                    </div>
                </div>
                <div class="form-group row" v-show="frequencyNever == false">
                    <label for="" class="col-xl-1 col-form-label">End</label>
                    <div class="col-xl-8">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="repeatEnd" id="rbEndNever" value="never" v-model="reserveRequest.repeatEnd">
                            <label class="form-check-label" for="rbEndNever">
                                Never
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="repeatEnd" id="rbEndAfter" value="after" v-model="reserveRequest.repeatEnd">
                            <label class="form-check-label" for="rbEndAfter">
                                After
                            </label>
                            <vue-number-input v-model="reserveRequest.endAfter"
                                              inline
                                              controls
                                              size="small"
                                              :disabled="!repeatEndAfter"
                                              :center="true"></vue-number-input> occurence(s)

                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="repeatEnd" id="rbEndOn" value="on" v-model="reserveRequest.repeatEnd">
                            <label class="form-check-label" for="rbEndOn">
                                On
                            </label>
                            <div class="col-xl-3">
                                <form-date-picker datepickerid="txtEndOn"
                                                  :inputdisabled="!repeatEndOn"
                                                  v-model="reserveRequest.repeatUntil"
                                                   :notyping="true"/>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="txtDescr" class="col-xl-1 col-form-label">Description</label>
                    <div class="col-sm-11">
                        <textarea rows="4" class="form-control" id="txtDescr" placeholder="Description" v-model="reserveRequest.descr"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="staticName" class="col-xl-1 col-form-label">Submitted By</label>
                    <div class="col-sm-11">
                        @ViewBag.User.DisplayName<br />
                        @ViewBag.User.Email

                    </div>
                </div>
                <div class="alert alert-danger  alert-dismissible" role="alert" v-show="errorSubmitting">
                    <strong>Error while submitting</strong>.  Try submitting again or contacting the ITSC for support.
                    <p>{{ error }}</p>
                    <button type="button" class="close" v-on:click="dismissAlert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <button type="button"
                        id="btnSubmit"
                        v-on:click="submitReservation"
                        :disabled="isSubmitting">
                    <template v-if="isSubmitting">
                        <i class="fas fa-spinner fa-spin"></i>
                    </template> Submit Reservation Request
                </button>
            </form>
        </div>
    </div>
</div>


@section mastercss {

    <environment excludes="Development">
        <link asp-href-include="~/assets/index-*.css" rel="stylesheet" media="all" />
    </environment>
}

@section masterjs{


    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/pages.reserve.index-*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/pages/reserve/index/index.js"></script>
    </environment>
}

src/web/Views/Reserve/Success.cshtml
@model AAE.RESS.Web.ViewModels.ReserveViewModel
@{
    ViewData["Title"] = "Reservation Request Submitted";
}

@section breadcrumbs {

    @if (Model.Resource.ResourceType == ResourceType.Room)
    {
        <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Rooms</a></li>
    }
    @if (Model.Resource.ResourceType == ResourceType.Equipment)
    {
        <li><a asp-controller="Type" asp-action="Index" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">Equipment</a></li>
    }
    <li><a asp-controller="Info" asp-action="Index" asp-route-url="@Model.Resource.Url" asp-route-type="@ViewContext.RouteData.Values["type"].ToString()">@Model.Resource.DisplayName</a></li>
    <li>Reservation Request Submitted</li>
}

<div class="uw-full-row">
    <div class="uw-row">


        <h1 class="page-title uw-mini-bar" id="hdr" runat="server">Reservation Request Submitted</h1>
    </div>
    <div class="uw-row">
        <div class="col-sm-12">
            <p>Your reservation request has been submitted successfully.  You will receive an email response back once it has been processed.</p>
            </div>
    </div>
    </div>